[package]
name = "todo-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.8"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
clap = { version = "4.5.10", features = ["derive"] }
color-eyre = "0.6.3"
log = "0.4.22"
